***NumPy offers the random module to work with random numbers.***

In [1]:
from numpy import random

x = random.randint(100)

print(x)

56


In [2]:
#The random module's rand() method returns a random float between 0 and 1.

In [3]:
from numpy import random

x = random.rand()

print(x)


0.8356054597390428


In [4]:
#the randint() method takes a size parameter where you can specify the shape of an array.

In [5]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[30 38 70 19 93]


In [6]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

In [7]:
from numpy import random

x=random.randint(100, size=(5,10))

print(x)

[[19 33  1 56 47 87  9  9 74 98]
 [54 38 39 39 46  9 55 80 75 29]
 [60 57 81 62 12 66 38 26 79 11]
 [ 1 80 12 52 13 54 53 91 50 97]
 [ 3 23 71 11 53 99 58 39 92 82]]


In [8]:
#The rand() method also allows you to specify the shape of the array
#Generate a 1-D array containing 5 random floats.

In [9]:
from numpy import random

x = random.rand(5)

print(x)

[0.02588729 0.30697948 0.42771646 0.11931367 0.86136903]


In [10]:
#Genrate random number form array
#The choice() method allows you to generate a random value based on an array of values.

In [11]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [12]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [13]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 7 7 3 7]
 [3 9 3 5 3]
 [9 9 5 9 5]]


In [14]:
#Data Distribution is a list of all possible values, and how often each value occurs
#A random distribution is a set of random numbers that follow a certain probability density function..

***Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.


The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0***

In [15]:
from numpy import random

In [16]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(100))

In [17]:
print(x)

[7 7 5 7 7 7 7 7 7 7 5 7 7 5 7 7 7 5 7 7 5 5 3 5 3 7 7 7 5 3 7 7 7 7 7 3 7
 5 7 7 5 7 7 7 7 5 7 7 5 5 7 7 7 5 3 5 5 5 7 5 5 7 7 7 5 3 7 7 5 7 7 5 7 7
 7 7 7 5 5 5 7 5 7 5 7 7 7 5 3 5 5 7 7 7 7 5 7 7 7 5]


In [18]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(3,5))

In [19]:
x

array([[7, 7, 7, 5, 5],
       [5, 7, 7, 7, 5],
       [5, 7, 5, 7, 3]])

In [20]:
#The shuffle() method makes changes to the original array..

In [21]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[4 2 1 3 5]


In [22]:
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [23]:
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 3 2 1 4]


In [24]:
l=['aish',1,2,3,4]

In [25]:
type(l)

list

In [26]:
type(np.array(l))

numpy.ndarray

In [27]:
a1=np.array([3,4,5,6,3.0])

In [28]:
a=np.array([[1,2],[3,4]])

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
a[1][1]

4

In [31]:
a1

array([3., 4., 5., 6., 3.])

In [32]:
a1[1]

4.0

In [33]:
a2=np.array([1,2,3,4],ndmin=4)

In [34]:
a2

array([[[[1, 2, 3, 4]]]])

In [35]:
a2[0][0][0][0]

1

In [36]:
a

array([[1, 2],
       [3, 4]])

In [37]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [40]:
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [41]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [42]:
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [43]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [44]:
np.fromfunction (lambda i ,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
np.fromfunction(lambda i ,j ,z,p:i*j*z*p,(4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [46]:
a

[1, 2, 3, 4, 5]

In [47]:
a=np.asarray(a)

In [48]:
a

array([1, 2, 3, 4, 5])

In [49]:
a.ndim

1

In [50]:
a.size

5

In [51]:
a.dtype

dtype('int32')

In [53]:
np.random.rand(100,4)

array([[0.90060757, 0.5679809 , 0.84734306, 0.02637472],
       [0.54294028, 0.40917189, 0.49435775, 0.64500411],
       [0.33050696, 0.20258933, 0.77294786, 0.70258124],
       [0.61451917, 0.95587875, 0.85851903, 0.29230982],
       [0.01906099, 0.69261523, 0.3931062 , 0.29866882],
       [0.16177642, 0.15485602, 0.30298706, 0.71647124],
       [0.17557271, 0.88038834, 0.13515523, 0.86855771],
       [0.29114881, 0.21268868, 0.5761338 , 0.52466709],
       [0.78407076, 0.97269789, 0.927447  , 0.00482832],
       [0.19508431, 0.65864404, 0.76618244, 0.1924288 ],
       [0.68975305, 0.71697986, 0.72949587, 0.98377515],
       [0.0322039 , 0.56991375, 0.16929506, 0.16417496],
       [0.61821602, 0.16894156, 0.71436072, 0.27646121],
       [0.37946435, 0.27169199, 0.73214191, 0.36560389],
       [0.42745991, 0.23524962, 0.91336496, 0.41088665],
       [0.88788293, 0.23564239, 0.34075547, 0.55215711],
       [0.95264462, 0.23801048, 0.54020907, 0.32852046],
       [0.55196818, 0.42072824,

In [55]:
import pandas as pd
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -0.053020 -0.215162 -2.125359  0.890400 -0.004343
1  0.676675  0.259581  0.681172  0.436434 -0.493018
2  0.597684 -1.996435 -0.719867  0.018052 -0.949673
3 -0.152326  0.232453 -0.166039 -1.398881 -0.805888

In [56]:
list(range(4,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

In [59]:
a1=np.arange(4,10.5,.2)

In [60]:
a1

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [61]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [62]:
arr=np.random.rand(4,5)

In [63]:
arr

array([[0.11247897, 0.94373797, 0.90322431, 0.26248585, 0.08060987],
       [0.65568267, 0.94926519, 0.09064402, 0.79452488, 0.60649614],
       [0.51361956, 0.64010699, 0.09681484, 0.10247393, 0.15757541],
       [0.28533437, 0.08914753, 0.62617796, 0.04711651, 0.62511722]])

In [65]:
arr[arr>.5]

array([0.94373797, 0.90322431, 0.65568267, 0.94926519, 0.79452488,
       0.60649614, 0.51361956, 0.64010699, 0.62617796, 0.62511722])

In [66]:
arr[[1,2],[2]]

array([0.09064402, 0.09681484])

In [67]:
arr=np.random.rand(8,5)

In [68]:
arr

array([[0.44080441, 0.74222996, 0.94813977, 0.4301282 , 0.07737609],
       [0.12258746, 0.9274592 , 0.39579912, 0.35808823, 0.1999058 ],
       [0.05195924, 0.259908  , 0.92907711, 0.5536524 , 0.02534617],
       [0.69890489, 0.70734146, 0.99732792, 0.34108296, 0.75246886],
       [0.29873517, 0.04996475, 0.57068635, 0.17921293, 0.43531463],
       [0.19902816, 0.32278643, 0.6679426 , 0.80521225, 0.64708499],
       [0.42932253, 0.15282689, 0.49646551, 0.60480284, 0.50089358],
       [0.65326667, 0.74715991, 0.34686073, 0.60828493, 0.36981436]])

In [69]:
arr[1:8,0:3]

array([[0.12258746, 0.9274592 , 0.39579912],
       [0.05195924, 0.259908  , 0.92907711],
       [0.69890489, 0.70734146, 0.99732792],
       [0.29873517, 0.04996475, 0.57068635],
       [0.19902816, 0.32278643, 0.6679426 ],
       [0.42932253, 0.15282689, 0.49646551],
       [0.65326667, 0.74715991, 0.34686073]])

In [70]:
a2 = arr[1:8 , [0,1,2]]

In [71]:
a2

array([[0.12258746, 0.9274592 , 0.39579912],
       [0.05195924, 0.259908  , 0.92907711],
       [0.69890489, 0.70734146, 0.99732792],
       [0.29873517, 0.04996475, 0.57068635],
       [0.19902816, 0.32278643, 0.6679426 ],
       [0.42932253, 0.15282689, 0.49646551],
       [0.65326667, 0.74715991, 0.34686073]])

In [72]:
a2[0][0]=100

In [73]:
a2

array([[1.00000000e+02, 9.27459200e-01, 3.95799124e-01],
       [5.19592424e-02, 2.59907998e-01, 9.29077106e-01],
       [6.98904885e-01, 7.07341462e-01, 9.97327919e-01],
       [2.98735174e-01, 4.99647453e-02, 5.70686347e-01],
       [1.99028164e-01, 3.22786426e-01, 6.67942596e-01],
       [4.29322532e-01, 1.52826889e-01, 4.96465511e-01],
       [6.53266673e-01, 7.47159914e-01, 3.46860733e-01]])

In [74]:
a = np.array([[1,2] ,[3,4]])
b = np.array([[2,3] , [4,5]])

In [75]:
a

array([[1, 2],
       [3, 4]])

In [76]:
b

array([[2, 3],
       [4, 5]])

In [77]:
a*b

array([[ 2,  6],
       [12, 20]])

In [78]:
m=a@b

In [79]:
m

array([[10, 13],
       [22, 29]])